image: node:latest

before_script:
  - ci/install-chrome.sh
  - npm install -g grunt-cli
  - npm install

build:
  script:
    - npm build

test:
  dependencies: build
  script:
    - xvfb-run -a npm test
  script:
  - xvfb-run -a npm test
