language: node_js
addons:
  apt:
    packages:
      - google-chrome-stable
node_js:
  - "stable"
before_install:
  - npm install -g grunt-cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
