language: node_js
sudo: true
addons:
  apt:
    packages:
      - google-chrome-stable
node_js:
  - "stable"
before_install:
  - npm install -g grunt-cli
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
